options(scipen = 9, digits = 10)
library(ggplot2)
source("mort functions.R")
library(MASS)
library(fitdistrplus)
library(vcd)
library(texreg)
x <- mortV1
descdist(x$deaths,boot=500,discrete=T,obs.col="blue", obs.pch = 15, boot.col="red")
descdist(x$pop,boot=500,discrete=T,obs.col="blue", obs.pch = 15, boot.col="red")
summary(nb <- fitdist(x$deaths, "nbinom"))
plot(foo<-goodfit(x$deaths,type = "nbinomial"), shade=F)
print(foo);summary(foo)
gofstat(nb,chisqbreaks = 0:9, discrete=T)
observed <- table(x$deaths)
foo  <- dnbinom(as.numeric(names(observed)), size = unname(nb$estimate[1]), mu = unname(nb$estimate[2])) * sum(observed)
rootogram(observed, foo)
(foo<-distplot(observed, type = "nbinomial"))
(foo<-Ord_plot(observed, type = "nbinomial"))
rm(nb,foo,observed)
v1.nb <- glm.nb(deaths ~ offset(log(1+pop)) + age + eth + gen + quin + dhb + year + pop, data = x)

x <- mortV2
descdist(x$deaths,boot=500,discrete=T,obs.col="blue", obs.pch = 15, boot.col="red")
descdist(x$pop,boot=500,discrete=T,obs.col="blue", obs.pch = 15, boot.col="red")
summary(nb <- fitdist(x$deaths, "nbinom"))
plot(foo<-goodfit(x$deaths,type = "nbinomial"), shade=F)
print(foo);summary(foo)
gofstat(nb,chisqbreaks = 0:8, discrete=T)
observed <- table(x$deaths)
foo  <- dnbinom(as.numeric(names(observed)), size = unname(nb$estimate[1]), mu = unname(nb$estimate[2])) * sum(observed)
rootogram(observed, foo)
(foo<-distplot(observed, type = "nbinomial"))
(foo<-Ord_plot(observed, type = "nbinomial"))
rm(nb,foo,observed)
v2.nb <- glm.nb(deaths ~ offset(log(1+pop)) + age + eth + gen + quin + dhb + year + pop, data = x)
AIC(v1.nb,v2.nb)
screenreg(list(v1.nb,v2.nb),single.row=T)
