options(scipen = 9, digits = 10)
library(ggplot2)
library(MASS)
library(fitdistrplus)
library(vcd)
library(texreg)
source("mort functions.R")
#source("DenomsApr16.R")
source("denomsV1-10Jun16.R")
source("denomsV2-10Jun16.R")
source("denomsV3-17Jun16.R")

x <- mortV1
descdist(x$deaths,boot=500,discrete=T,obs.col="blue", obs.pch = 15, boot.col="red")
descdist(x$pop,boot=500,discrete=T,obs.col="blue", obs.pch = 15, boot.col="red")
summary(nb <- fitdist(x$deaths, "nbinom"))
plot(foo<-goodfit(x$deaths,type = "nbinomial"), shade=F)
print(foo);summary(foo)
fv1 <- resid(foo)
gofstat(nb,chisqbreaks = 0:7, discrete=T)
observed <- table(x$deaths)
foo  <- dnbinom(as.numeric(names(observed)), size = unname(nb$estimate[1]), mu = unname(nb$estimate[2])) * sum(observed)
rootogram(observed, foo)
(foo<-distplot(observed, type = "nbinomial"))
(foo<-Ord_plot(observed, type = "nbinomial"))
rm(nb,foo,observed)
v1.nb <- glm.nb(deaths ~ offset(log(1+pop)) + age + eth + gen + quin + dhb + year + pop, data = x)

x <- mortV2
descdist(x$deaths,boot=500,discrete=T,obs.col="blue", obs.pch = 15, boot.col="red")
descdist(x$pop,boot=500,discrete=T,obs.col="blue", obs.pch = 15, boot.col="red")
summary(nb <- fitdist(x$deaths, "nbinom"))
plot(foo<-goodfit(x$deaths,type = "nbinomial"), shade=F)
print(foo);summary(foo)
fv2 <- resid(foo)
gofstat(nb,chisqbreaks = 0:7, discrete=T)
observed <- table(x$deaths)
foo  <- dnbinom(as.numeric(names(observed)), size = unname(nb$estimate[1]), mu = unname(nb$estimate[2])) * sum(observed)
rootogram(observed, foo)
(foo<-distplot(observed, type = "nbinomial"))
(foo<-Ord_plot(observed, type = "nbinomial"))
rm(nb,foo,observed)
v2.nb <- glm.nb(deaths ~ offset(log(1+pop)) + age + eth + gen + quin + dhb + year + pop, data = x)


x <- mortV3
descdist(x$deaths,boot=500,discrete=T,obs.col="blue", obs.pch = 15, boot.col="red")
descdist(x$pop,boot=500,discrete=T,obs.col="blue", obs.pch = 15, boot.col="red")
summary(nb <- fitdist(x$deaths, "nbinom"))
plot(foo<-goodfit(x$deaths,type = "nbinomial"), shade=F)
print(foo);summary(foo)
gofstat(nb,chisqbreaks = 0:7, discrete=T)
fv3 <- resid(foo)
observed <- table(x$deaths)
foo  <- dnbinom(as.numeric(names(observed)), size = unname(nb$estimate[1]), mu = unname(nb$estimate[2])) * sum(observed)
rootogram(observed, foo)
(foo<-distplot(observed, type = "nbinomial"))
(foo<-Ord_plot(observed, type = "nbinomial"))
rm(nb,foo,observed)
v3.nb <- glm.nb(deaths ~ offset(log(1+pop)) + age + eth + gen + quin + dhb + year + pop, data = x)
AIC(v1.nb,v2.nb,v3.nb)
screenreg(list(v1.nb,v2.nb,v3.nb),single.row=T)


V1 <- aggregate(cbind(deaths, pop) ~ dhb, mortV1, FUN=sum)
V2 <- aggregate(cbind(deaths, pop) ~ dhb, mortV2, FUN=sum)
V3 <- aggregate(cbind(deaths, pop) ~ dhb, mortV3, FUN=sum)
a <- glmer.nb (deaths ~ offset(log(1+pop)) + year + (1|dhb) + (0 + year |dhb), data = mortV3)

res.comp <- data.frame(res.v1 = fv1, res.v2 = fv2, res.v3 = fv3, count = 0:10)
plot(1, type="n", xlab="", ylab="", xlim=c(0, 10), ylim=c(-5, 5))
# overlay predicted values
lines(x = res.comp$count, y = res.comp$res.v1, type = "b", lwd=2, lty=1, col="black")
lines(x = seq(0, 10, 1), y = res.comp$res.v2, type = "b", lwd=2, lty=2, col="red")
lines(x = seq(0, 10, 1), y = res.comp$res.v3, type = "b", lwd=2, lty=3, col="blue")
